### ISSUE TITLE
release version 6

### ISSUE THREAD

**Issue by dhellmann** [python-virtualenvwrapper/virtualenvwrapper#19]
We need to skip 5 because we had the broken package with that version some time back.

**Comment by dhellmann** [comment]
Alpha version published https://github.com/python-virtualenvwrapper/virtualenvwrapper/releases/tag/6.0.0.0a1

**Comment by dhellmann** [comment]
Second alpha published https://github.com/python-virtualenvwrapper/virtualenvwrapper/releases/tag/6.0.0.0a2

**Comment by dhellmann** [comment]
@jasonamyers we've had the alpha out for 2 months, what do you think about making it official?

**Comment by carltongibson** [comment]
I think this can be closed now 😉
