### ISSUE TITLE
archive old repo on bitbucket

### ISSUE THREAD

**Issue by dhellmann** [python-virtualenvwrapper/virtualenvwrapper#25]

**Comment by dhellmann** [comment]
I marked the repo as private for now, in case we want to review any of the other bugs or PRs that I closed. We can delete it and set up the redirect to the new location after a few days.

**Comment by dhellmann** [comment]
I have deleted the old repository and "virtualenvwrapper" workspace and gave a link to this one to be displayed when someone visits

**Comment by jessamynsmith** [comment]
Hi @dhellmann I apologize, the invitation escaped my notice. If you care to re-invite me, I will join.

**Comment by dhellmann** [comment]
No problem, @jessamynsmith , I've sent another invitation.
