### ISSUE TITLE
Is there a way to ask virtualenvwrapper its version number?

### ISSUE THREAD

**Issue by nedbat** [python-virtualenvwrapper/virtualenvwrapper#42]
I think I'm trying 6.0.0.0a1, but I don't know.. `virtualenvwrapper --version` doesn't show a version, and there doesn't seem to be a version number in the .sh.

**Comment by dhellmann** [comment]
That's a great question. We should have some sort of version command.

In the mean time, if you don't trust the results of `pip freeze`, another way to tell for this specific version is if `toggleglobalsitepackages` is defined as a shell function. You'll want to check using a clean shell session with only this version of virtualenvwrapper.sh sourced (i.e., not a shell you've been using and upgraded). Removing that command is one of the breaking changes in this release.
