### ISSUE TITLE
Virtualenvwrapper creates virtual env with wrong python interpreter

### ISSUE THREAD

**Issue by valentingregoire** [python-virtualenvwrapper/virtualenvwrapper#44]
In Ubuntu 22.04 using zsh, I get this weird behavior. I have pyenv installed with a Python 3.8.10 shim installed. I have this config in my `.zshrc`: 
```bash
#virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=~/.pyenv/shims/python
source $HOME/.local/bin/virtualenvwrapper.sh
```

The shim is pointing to the correct location:
```bash
❯ ~/.pyenv/shims/python --version
Python 3.8.10
```

Yet, when I create a virtual environment, I receive this output (this is only a fragment):
```bash
❯ mkvirtualenv a
created virtual environment CPython3.10.6.final.0-64 in 76ms
...
```

When I activate the environment and ask for the python version, I get this:
```bash
❯ python --version
Python 3.10.6
```

When I debug the `virtualenwvrapper.sh`, I see that the very beginning of the script is fetching the location of the python installation. When I put an echo after that little block of code, I see this as an output:
```shell
before setting VIRTUALENVWRAPPER_PYTHON: /home/valentin/.pyenv/shims/python
after setting VIRTUALENVWRAPPER_PYTHON: /home/valentin/.pyenv/shims/python
```

I don't understand that my virtual envs are pointing tot Python `3.10.6` while everything is pointing to `3.8.10`. What am I doing wrong?

**Comment by dhellmann** [comment]
The most important factor is where virtualenv itself is installed. What does $VIRTUALENVWRAPPER_VIRTUALENV point to? What does "which virtualenv" report?

**Comment by valentingregoire** [comment]
When I `echo $VIRTUALENVWRAPPER_VIRTUALENV`, the output is: `virtualenv`. When I do `which virtualenv`, I get:
 ```bash
/home/valentin/.local/bin/virtualenv
```

When I do `which virtualenv`, I get:
```bash
/home/valentin/.local/bin/virtualenv
/home/valentin/.pyenv/shims/virtualenv
```
So for some reason, there is an installation virtualenv in my `.local/bin` folder. There is no `python`, `python3`, `pip` nor `pip3` command to be found in `.local/bin`.

`pip` and `pip3` only can be found in my `shim` folder. So I don't know how to remove the `virtualenv` installation in the `.local/bin` folder. Or is that not the approach to go?

**Comment by dhellmann** [comment]
Usually things end up in `~/.local` if you use the `--user` flag to `pip install`. Running `pip uninstall virtualenv` may remove that file, along with the rest of the package (it should show you what it is going to remove). After doing that, you could then install virtualenv using the python interpreter you want to have it use.

**Comment by valentingregoire** [comment]
After uninstalling `virtualenv` and installing it with `--user`, it seems like my environments are working perfectly. Even though I had installed it from the shims (without `--user`), still the `virtualenv` ended up in the wrong location. Thanks for the help!!
