### ISSUE TITLE
virtualenwrapper.user_scripts not finding preactivate and other files

### ISSUE THREAD

**Issue by YolCruz** [python-virtualenvwrapper/virtualenvwrapper#56]
## TL;DR: 
virtualenvwrapper.user_scripts can't find files like preactivate even tho they exist.

### Details

I installed virtualenvwrapper with brew. After shell restart I see the following output:

```
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/premkproject
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/postmkproject
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/initialize
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/premkvirtualenv
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/postmkvirtualenv
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/prermvirtualenv
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/postrmvirtualenv
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/predeactivate
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/postdeactivate
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/preactivate
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/postactivate
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/get_env_details
```

I run the command `mkvirtualenv test`, this is the output that I see:

```
created virtual environment CPython3.11.2.final.0-64 in 165ms
  creator CPython3Posix(dest=/Users/yolcruz/.virtualenvs/test, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/yolcruz/Library/Application Support/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/test/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/test/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/test/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/yolcruz/.virtualenvs/test/bin/get_env_details
virtualenvwrapper.user_scripts could not run "/Users/yolcruz/.virtualenvs/premkvirtualenv": [Errno 2] No such file or directory: '/Users/yolcruz/.virtualenvs/premkvirtualenv'
virtualenvwrapper.user_scripts could not run "/Users/yolcruz/.virtualenvs/preactivate": [Errno 2] No such file or directory: '/Users/yolcruz/.virtualenvs/preactivate'
virtualenvwrapper.user_scripts could not run "/Users/yolcruz/.virtualenvs/test/bin/preactivate": [Errno 2] No such file or directory: '/Users/yolcruz/.virtualenvs/test/bin/preactivate'
```

As you can see, virtualenvwrapper.user_scripts can't find some files that itself said it was going to create. And they are actually there in my system:

```
$ ls -a1 ~/.virtualenvs/
.
..
get_env_details
initialize
postactivate
postdeactivate
postmkproject
postmkvirtualenv
postrmvirtualenv
preactivate
predeactivate
premkproject
premkvirtualenv
prermvirtualenv
test
```

```
$ ls -a1 ~/.virtualenvs/test/bin/
.
..
activate
activate.csh
activate.fish
activate.nu
activate.ps1
activate_this.py
get_env_details
pip
pip-3.11
pip3
pip3.11
postactivate
postdeactivate
preactivate
predeactivate
python
python3
python3.11
wheel
wheel-3.11
wheel3
wheel3.11
```

### Info

I have the following env variables:

```
VIRTUALENVWRAPPER_PYTHON=/opt/homebrew/Cellar/virtualenvwrapper/4.8.4_2/libexec/bin/python3.11
VIRTUALENVWRAPPER_PROJECT_FILENAME=.project
VIRTUALENVWRAPPER_WORKON_CD=1
VIRTUALENVWRAPPER_SCRIPT=/opt/homebrew/Cellar/virtualenvwrapper/4.8.4_2/libexec/bin/virtualenvwrapper.sh
WORKON_HOME=/Users/yolcruz/.virtualenvs
VIRTUALENVWRAPPER_HOOK_DIR=/Users/yolcruz/.virtualenvs
```
I have also tried using `pip install virtualenvwrapper` but I get the same error

How could I fix this?

**Comment by dhellmann** [comment]
If you set VIRTUALENVWRAPPER_LOG_FILE to point to a file, the hook loader should log debug output there and that may offer some hints.

**Comment by dhellmann** [comment]
It would also be useful to see the contents of one of the hooks, such as `/Users/yolcruz/.virtualenvs/premkvirtualenv`

**Comment by dhellmann** [comment]
Oh, and which shell are you using?

**Comment by ironfroggy** [comment]
I'm having this same problem, and I'm using zsh but also tried and it got the same via bash.

**Comment by dhellmann** [comment]
Are the hooks regular files or symlinks?

If you run the hook by hand what output does it produce?

**Comment by pederkl** [comment]
I saw the same thing yesterday, the cause turned out to be that the hook scripts all started with `#!bash`, not the expected `#!/bin/zsh`.  Reading `user_scripts.py` I think the only way that could have happened is if `os.environ.get('SHELL')` returned 'bash', but I don't know how that could have happened.  I can't reproduce the error, `mkvirtualenv` today creates fully functional virtualenvs with `#!/bin/zsh` in the hooks (my machine has booted in the interim, so my non-virtual environment is fresh and clean).

The fix for the problem env created yesterday (other than deleting and recreating with todays functional commands) was to run:

```shell
$ cd $VIRTUAL_ENV/bin
$ find . -maxdepth 1 -type f | xargs sed -i 's|#!bash|#!/bin/zsh|'
```
This replaces the `#!bash` with `#!/bin/zsh`.  For bash users, the substitution would be to `/bin/bash` instead.

Perhaps `user_scripts.py` could have a sanity check that the `SHELL` found is an absolute path that exists?  Or perhaps sanity checking users' global environments is outside the scope of virtualenvwrapper.  Not for me to decide.

**Comment by dhellmann** [comment]
This ticket has been open for a while with no response, so I am closing it. Let us know if you are still having this problem.
