### ISSUE TITLE
set up GitHub action for publishing releases, including tests

### ISSUE THREAD

**Issue by dhellmann** [python-virtualenvwrapper/virtualenvwrapper#6]

**Comment by dhellmann** [comment]
@jasonamyers in order to complete this, I need admin permission on test.pypi.org so I can generate an API key.

https://test.pypi.org/project/virtualenvwrapper/

**Comment by jasonamyers** [comment]
sent

**Comment by dhellmann** [comment]
Based on https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ it looks like it is no longer possible to test package uploads. That's probably just as well. We have a pkglint job in place, so that should be sufficient. #40 fixes up the job settings based on the latest instructions, and we can test with a pre-release tag when that merges.

**Comment by dhellmann** [comment]
Based on https://docs.openstack.org/pbr/latest/user/semver.html I chose the version 6.0.0.0a1 as a test version.

At commit d7cb9b855a4d64b5dccd2968b320f75ada98fcc1 I ran

```
$ git tag -s -m 'test release action' 6.0.0.0a1
$ git push origin 6.0.0.0a1
```

That produced https://pypi.org/project/virtualenvwrapper/6.0.0.0a1/
