### ISSUE TITLE
Usage of egrep in virtualenvwrapper.sh

### ISSUE THREAD

**Issue by valentingregoirebasf** [python-virtualenvwrapper/virtualenvwrapper#62]
On Fedora 38, when sourcing `virtualenvwrapper.sh` in my `.zshrc` file, I receive a warning:
```
egrep: warning: egrep is obsolescent; using grep -E
```

**Comment by mogoh** [comment]
Fix is already in the changelog: https://github.com/python-virtualenvwrapper/virtualenvwrapper/blob/main/docs/source/history.rst#6000a1

**Comment by remidebette** [comment]
Hi, is the version 6 going to get released?

**Comment by dhellmann** [comment]
I fixed up some packaging issues and released 6.0.0.0a5 today. I'll let that sit for a bit before publishing the official release. Give it a try, please, and let me know if this issue is resolved.

**Comment by dhellmann** [comment]
Closing as fixed.

**Comment by remidebette** [comment]
All good now, thank you
