### ISSUE TITLE
toggleglobalsitepackages capability

### ISSUE THREAD

**Issue by SiggyF** [python-virtualenvwrapper/virtualenvwrapper#63]
On my platform (macports, py310, py310-virtualenv) the `toggleglobalsitepackages` is no longer working.  
Virtualenvwrapper creates an environment with CPython3Posix. This results in a virtualenv with a `pyvenv.cfg` file. 
This `pyvenv.cfg` now contains the setting `include-system-site-packages = false`. It no longer seems to look at the `no-global-site-packages.txt` which is generated/removed by the `toggleglobalsitepackages`. 

I noticed that in the current master  this function is being removed. I think it could be re-implemented to toggle the value in the pyvenv.cfg. 

### Proposed solution
I think the `include-system-site-packages = false` should be changed when the `toggleglobalsitepackages` function is called. 

### Notes
I'd be happy to prepare a pull request if you agree with the proposed solution. Would a "grep" / "sed" call be the expected implementation (as the other functions are implemented in sh)?

**Comment by dhellmann** [comment]
That feature has been removed from newer versions of virtualenvwrapper in d9f58eafadebdd713b60c0edc29a9b4f047c799a, in part because it appeared to have been removed from virtualenv.

**Comment by dhellmann** [comment]
I'm going to close this as something we don't expect to fix. If virtualenv is updated to include the underlying feature again, we could look at bringing it back.
