### ISSUE TITLE
Virtualenvwrapper workon if .venv is inside project folder

### ISSUE THREAD

**Issue by matejsp** [python-virtualenvwrapper/virtualenvwrapper#77]
I have a lot of projects on my computer ... some use ~/.virtualens and some use project/.venv
In case I want to workon with a project that has .venv file or .venv folder it should use that.
```
workon . -> resolves to project folder name
workon .venv -> unable to find .venv
```
```
➜  project workon .
ERROR: Environment 'project' does not exist. Create it with 'mkvirtualenv project'.
```

I would expect if there is .venv inside the folder that it would activate it and not search for global virtualenvs.

**Comment by matejsp** [comment]
one workaround is (but it is anoying):
```
WORKON_HOME=. workon .venv
```

**Comment by matejsp** [comment]
https://docs.python.org/3/library/venv.html

```
Contained in a directory, conventionally either named venv or .venv in the project directory, or under a container directory for lots of virtual environments, such as ~/.virtualenvs.
```

**Comment by dhellmann** [comment]
I'm not sure this is a feature we want. The idea with virtualenvwrapper is that you let it manage the environment directories, so they won't be scattered around and created in different ways to begin with. If I misunderstood, please reopen the ticket with more details.

**Comment by matejsp** [comment]
Basically I wanted virtualenvwrapper to additionally support also officially recommended way: 
https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#create-and-use-virtual-environments
> To create a virtual environment, go to your project’s directory and run the following command. This will create a new virtual environment in a local folder named .venv:

The point of this issue was to support similar feature a in ohmyzsh plugin: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh#L45-L54
They check for .venv file content, then for .venv folder and last by project name. 

I understand the point of your project is to have better alternative (having all virtualenvs at one place). But my proposal was to be compatible with recommended way if you to have single command to switch between environment.

Image you have a developer with couple of projects using .venv inside their project folder (like in latest python guide).
Then they come across your project and want to try it out. Now if you support both ways they are not forced to migrate all project at once but can do it at their own convenience. For example some projects that we use have sh scripts that rely on having venv in .venv folder. We can and did add support also your way and official way (for production) but it takes time for all projects.

I cannot reopen this ticket.

**Comment by dhellmann** [comment]
OK. Virtualenvwrapper predates that advice. There are other tools out there that use the approach described, and may be a better fit for what you're trying to do.
