### ISSUE TITLE
Incomplete installation

### ISSUE THREAD

**Issue by buhtz** [python-virtualenvwrapper/virtualenvwrapper#95]
Hello,
technically I do but from a usability perspective I do not understand why the users have to `source .../wirtualenvwrapper.sh`? Can't this be somehow done via installation?

You still using entry-points for some tasks. Why not creating entry-points for the regular commands like `mkvirtualenv`? Wouldn't his be an acceptable solution?

Kind

**Comment by dhellmann** [comment]
There's no interface for pip to use to add something to your login shell, unfortunately, so it cannot be done as part of installing the package. If an OS vendor wanted to do that as part of their RPM/deb/whatever package, that would be up to them.

The various commands could technically be implemented as plugins, but it seems like it would be more work to build and debug them that way. What benefit do you anticipate?

**Comment by carltongibson** [comment]
This doesn't really seem like an addressable issue as it stands?
